spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/redistest
    username: root
    password: hunil@3751
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      show_sql: true
      format_sql: true
    logging.level:
      org.hibernate.SQL: debug